/*
 * This file contains functions relating to the socket connection between a
 * client and the SXWM window manager.
 */

#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/un.h>

 /*
 * Determine the default location of the SXWM socket. Write the path in the
 * destination buffer up to 108 bytes.
 *
 * We combine the name of the default display (from the DISPLAY environment
 * variable) with constant strings to make /tmp/sxwm:X.sock.
 *
 * On success returns the length of the string written in the buffer,
 *                    including the terminating null byte.
 * On failure returns -1 and sets errno to indicate the error.
 *
 * Errors:
 *  ENAMETOOLONG: The calculated name would not fit in a 108 byte buffer.
 *  EINVAL: The environment variable DISPLAY is not set.
 */
int SXWMDefaultSocketPath(char *buffer)
{
	char *displayName = getenv("DISPLAY");
	if (!displayName) {
		errno = EINVAL;
		return -1;
	}
	int displayNameLen = strlen(displayName);
	if (displayNameLen > 93) {
		errno = ENAMETOOLONG;
		return -1;
	}

	memcpy(buffer, "/tmp/sxwm", 9);
	memcpy(buffer + 9, displayName, displayNameLen);
	strcpy(buffer + 9 + displayNameLen, ".sock");

	return 15 + displayNameLen;
}

/*
 * Create a socket and connect to SXWM at the given socket path. If no path is
 * given, then a default path is generated based on the name of the display.
 *
 * On success returns the file descriptor associated with the connection.
 * On failure returns -1 and sets errno to indicate the error.
 *
 * Errors:
 *  ENAMETOOLONG: The calculated name would not fit in a 108 byte buffer.
 *  EINVAL: The environment variable DISPLAY is not set.
 * Other errors may be generated by socket(2) and connect(2).
 */
int SXWMConnectSocket(const char *path)
{
	struct sockaddr_un sock;
	sock.sun_family = AF_UNIX;

	if (path) {
		/* The sockaddr_un.sun_path is 108 bytes long, we can therefore
		 * only fit 107 bytes. */
		int len = strlen(path);
		if (len > 107) {
			errno = ENAMETOOLONG;
			return -1;
		}

		strcpy(sock.sun_path, path);
	} else {
		/* Choose the default name if none is given. */
		if (SXWMDefaultSocketPath(sock.sun_path) < 0) {
			return -1;
		}
	}

	/* Create and connect the socket. */
	int fd = socket(AF_UNIX, SOCK_STREAM, 0);
	if (fd < 0) {
		return -1;
	}
	if (connect(fd, (struct sockaddr*)&sock, sizeof(struct sockaddr_un))) {
		return -1;
	}

	return fd;
}